//! Peer-mesh routing dispatcher.
//!
//! A [`Router<I>`] owns the routing decision tree (direct / relay /
//! redial) for one node. Transports delegate every send and every
//! inbound dispatch to it via [`Router::send_to_peer`] /
//! [`Router::process_inbound`] / [`Router::process_inbound_sync`],
//! supplying a per-peer connection map keyed by id whose values
//! implement [`OutboundChannel<I>`]. The Router never holds transport
//! state and never dials peers — it returns a [`SendOutcome`] /
//! [`InboundOutcome`] that signals when the transport should kick a
//! redial; the transport implements that side of the boundary.
//!
//! All log lines on the relay path use `target: RELAY_LOG_TARGET`
//! ("dynrunner_relay") so an operator running with
//! `RUST_LOG=dynrunner_relay=info` sees the relay-path events
//! regardless of which crate the code happens to live in.
//!
//! # Concurrency
//!
//! Caller invariant: at most one in-flight `send_to_peer` /
//! `process_inbound` / `process_inbound_sync` call per Router. The
//! `&mut self` shape of every public method enforces this
//! structurally; the field-level split-borrow pattern inside each
//! method (e.g. `outgoing_relays.get_mut(&key)` held alongside
//! `&self.failed_forwarders`) only works because no concurrent
//! borrow exists. Future maintainers wanting reentrant-safe Router
//! must add a lock at the entry points.

use std::collections::HashMap;
use std::time::Instant;

use dynrunner_core::Identifier;

use crate::messages::DistributedMessage;
use crate::relay::channel::OutboundChannel;
use crate::relay::router::state::{
    Clocks, InboundOutcome, PeerRouteState, RELAY_LOG_TARGET, RoutingError, SendOutcome,
    blacklist_for, prune_blacklist, prune_stale,
};
use crate::relay::{OutgoingRelay, RouteDecision, forward_step, route_send};

/// Single owner of peer-mesh routing decisions for one node.
///
/// The transport supplies a per-peer connection map (with values that
/// implement [`OutboundChannel<I>`]) and a [`Clocks`] snapshot on each
/// call. Router never reads the system clock and never holds
/// transport-specific state — so test drivers can simulate partitions
/// by mutating the connection map directly, and `tokio::time::pause`'d
/// scenarios drive the cooldown gate without races.
pub struct Router<I: Identifier> {
    pub(super) self_id: String,
    /// Monotonic counter for relay ids generated by this node as
    /// originator. Forwarders never allocate — they preserve the
    /// originator's id.
    pub(super) next_relay_id: u64,
    /// In-flight relays we've sent (originator) or forwarded
    /// (forwarder). Keyed by `(original_sender, relay_id)` so two
    /// originators using overlapping monotonic counters don't
    /// collide. The TTL sweep prunes entries whose `last_used_at` is
    /// older than `RELAY_STATE_TTL` so silent successes don't leak
    /// memory.
    pub(super) outgoing_relays: HashMap<(String, u64), OutgoingRelay<I>>,
    /// Cross-relay blacklist of forwarders that recently bounced a
    /// relay back. Keyed by `(target, forwarder)`: a forwarder F that
    /// failed to deliver to target T1 is NOT also blacklisted for
    /// target T2 — the partition that broke F→T1 may not affect F→T2.
    /// Entries expire after `BLACKLIST_TTL` so a direct link
    /// re-established in the meantime gets re-tried rather than
    /// shadowed forever.
    pub(super) failed_forwarders: HashMap<(String, String), Instant>,
    /// Per-target route observation: drives the only logging on the
    /// relay path (direct→relay, relay→relay, relay→direct) AND
    /// carries `last_observed_relay_at`, the redial-cooldown gate's
    /// single source of truth for "when did we last observe an active
    /// relay relationship with this peer?". Direct-only traffic does
    /// NOT touch the timestamp; only Relay outcomes (send-side) and
    /// Relay envelopes addressed to us (recv-side) do.
    pub(super) route_state: HashMap<String, PeerRouteState>,
}

impl<I: Identifier> Router<I> {
    /// Construct an empty Router for the node identified by `self_id`.
    pub fn new(self_id: String) -> Self {
        Self {
            self_id,
            next_relay_id: 0,
            outgoing_relays: HashMap::new(),
            failed_forwarders: HashMap::new(),
            route_state: HashMap::new(),
        }
    }

    /// Sweep TTL'd state. Idempotent and cheap; safe to call from
    /// every entry point. Pre-fix-baseline: only `send_to_peer` would
    /// prune outgoing_relays, so a node that only *forwarded* (never
    /// *originated* sends) grew the relay map without bound. Calling
    /// this from every entry point bounds memory by the union of
    /// recent activity regardless of which side of the duplex was
    /// last touched.
    pub fn prune(&mut self, now: Instant) {
        prune_stale(&mut self.outgoing_relays, now);
        prune_blacklist(&mut self.failed_forwarders, now);
    }

    /// Originate a send to `target`. Routes via direct or relay,
    /// dispatches via `connections`, commits state on success, and
    /// emits the redial signal when the cooldown gate trips.
    ///
    /// On dispatch failure (channel closed) the dead channel is
    /// removed from `connections` and the failure is propagated as
    /// `RoutingError::DispatchFailed`.
    ///
    /// Caller invariant: at most one in-flight call per Router
    /// (`&mut self` enforces this structurally).
    pub fn send_to_peer<C: OutboundChannel<I>>(
        &mut self,
        target: &str,
        msg: DistributedMessage<I>,
        connections: &mut HashMap<String, C>,
        clocks: Clocks,
    ) -> Result<SendOutcome, RoutingError> {
        let relay_id = self.next_relay_id;
        let blacklist = blacklist_for(&self.failed_forwarders, target, clocks.now);
        let decision = route_send(
            connections,
            &self.self_id,
            target,
            relay_id,
            msg,
            clocks.wire,
            &blacklist,
        );
        match decision {
            RouteDecision::Direct(direct) => {
                let send_res = connections
                    .get(target)
                    .map(|chan| chan.dispatch(direct))
                    .ok_or_else(|| RoutingError::NoConnection {
                        peer: target.to_string(),
                    })?;
                if send_res.is_err() {
                    connections.remove(target);
                    return Err(RoutingError::DispatchFailed {
                        peer: target.to_string(),
                        context: "direct send: connection closed".to_string(),
                    });
                }
                self.observe_direct(target);
                Ok(SendOutcome::Direct)
            }
            RouteDecision::Relay {
                via,
                wrapped,
                bookkeeping,
            } => {
                let send_res = connections
                    .get(&via)
                    .map(|chan| chan.dispatch(wrapped))
                    .ok_or_else(|| RoutingError::NoConnection { peer: via.clone() })?;
                if send_res.is_err() {
                    connections.remove(&via);
                    return Err(RoutingError::DispatchFailed {
                        peer: via.clone(),
                        context: format!(
                            "relay forwarder connection closed during send to '{target}'"
                        ),
                    });
                }
                self.next_relay_id = self.next_relay_id.wrapping_add(1);
                self.outgoing_relays
                    .insert((self.self_id.clone(), relay_id), bookkeeping);
                let redial_target = self.observe_relay(target, &via, clocks.now);
                Ok(SendOutcome::Relayed {
                    forwarder: via,
                    redial_target,
                })
            }
            RouteDecision::NoRoute => Ok(SendOutcome::NoRoute),
        }
    }

    /// Async-safe inbound dispatch. Handles `Relay` / `RelayBackoff`
    /// envelopes internally (forward via `connections`, retry on
    /// backoff, drop on dead-end). Returns
    /// [`InboundOutcome::Deliver`] for non-routing variants and for
    /// `Relay` envelopes addressed to us; `Relay`-for-us
    /// additionally bumps `last_observed_relay_at[original_sender]`
    /// (receiver-side observation) and emits `redial_target` if the
    /// cooldown gate trips.
    pub fn process_inbound<C: OutboundChannel<I>>(
        &mut self,
        msg: DistributedMessage<I>,
        connections: &mut HashMap<String, C>,
        clocks: Clocks,
    ) -> InboundOutcome<I> {
        match msg {
            DistributedMessage::Relay {
                sender_id,
                timestamp,
                target_id,
                relay_id,
                path,
                inner,
            } => {
                if target_id == self.self_id {
                    // Receiver-side observation: the original sender
                    // is reaching us via relay, so we have an active
                    // relay relationship with them. Bump the cooldown
                    // gate against `sender_id` (the wire envelope's
                    // sender_id is the originator, not the immediate
                    // predecessor — see route_send/forward_step which
                    // preserve sender_id end-to-end), and emit
                    // redial_target if the gate trips.
                    //
                    // We do NOT touch `route_state[sender_id].via`:
                    // `via` represents OUR outbound route to the peer,
                    // which is only knowable from our send-side
                    // experience. Their→us being broken does not
                    // imply ours→them is broken (asymmetric
                    // partition); overwriting `via` here would
                    // produce a spurious direct→relay warn the next
                    // time we send to them while our direct link
                    // still works. The path argument is unused for
                    // the same reason.
                    let _ = path;
                    let redial_target = self.observe_relay_recv(&sender_id, clocks.now);
                    return InboundOutcome::Deliver {
                        // `inner` is already `Box<DistributedMessage<I>>`;
                        // forward the existing allocation.
                        msg: inner,
                        redial_target,
                    };
                }
                let blacklist = blacklist_for(&self.failed_forwarders, &target_id, clocks.now);
                let decision = forward_step(
                    connections,
                    &self.self_id,
                    &target_id,
                    relay_id,
                    &path,
                    timestamp,
                    &sender_id,
                    inner,
                    &blacklist,
                );
                self.apply_forward_decision(
                    decision,
                    sender_id,
                    relay_id,
                    target_id,
                    path,
                    connections,
                    clocks,
                );
                InboundOutcome::Handled {
                    redial_target: None,
                }
            }
            DistributedMessage::RelayBackoff {
                sender_id: failed_via,
                timestamp: _,
                original_sender,
                relay_id,
            } => {
                self.handle_inbound_backoff(
                    original_sender,
                    relay_id,
                    failed_via,
                    connections,
                    clocks,
                );
                InboundOutcome::Handled {
                    redial_target: None,
                }
            }
            other => InboundOutcome::Deliver {
                msg: Box::new(other),
                redial_target: None,
            },
        }
    }

    /// Sync inbound dispatch for fast-path try-recv loops.
    ///
    /// Cannot forward `Relay` envelopes addressed to others, because
    /// forwarding requires both state mutation AND outbound dispatch
    /// against the connections map; preserved-from-pre-refactor
    /// behavior is to drop them with a warn. `RelayBackoff` is
    /// dropped silently for the same reason.
    ///
    /// `Relay` envelopes addressed to us are unwrapped and delivered,
    /// AND the receiver-side cooldown gate fires — bookkeeping is
    /// pure state mutation, no outbound dispatch needed, so nothing
    /// in the sync constraint excludes it. (Pre-A3.M1 this branch
    /// suppressed the redial signal, leaving a latent gap if a
    /// consumer ever drove recv via try_recv only.)
    pub fn process_inbound_sync(
        &mut self,
        msg: DistributedMessage<I>,
        clocks: Clocks,
    ) -> InboundOutcome<I> {
        match msg {
            DistributedMessage::Relay {
                sender_id,
                target_id,
                inner,
                ..
            } if target_id == self.self_id => {
                let redial_target = self.observe_relay_recv(&sender_id, clocks.now);
                InboundOutcome::Deliver {
                    // `inner` is already `Box<DistributedMessage<I>>`;
                    // forward the existing allocation.
                    msg: inner,
                    redial_target,
                }
            }
            DistributedMessage::Relay { target_id, .. } => {
                tracing::warn!(
                    target: RELAY_LOG_TARGET,
                    target_peer = %target_id,
                    "try_recv path dropped relay: cannot forward synchronously, use recv_peer"
                );
                InboundOutcome::Handled {
                    redial_target: None,
                }
            }
            DistributedMessage::RelayBackoff { .. } => InboundOutcome::Handled {
                redial_target: None,
            },
            other => InboundOutcome::Deliver {
                msg: Box::new(other),
                redial_target: None,
            },
        }
    }

    /// Inspect the per-peer route observation map.
    ///
    /// Exposed for cross-crate tests (`dynrunner-transport-channel`'s
    /// `tests/mesh_partition.rs`) so partition / heal scenarios can
    /// assert on `last_observed_relay_at` directly without round-
    /// tripping through `SendOutcome`. Gated behind the `test-utils`
    /// feature so production builds cannot accidentally depend on
    /// internal routing state — flip the feature on in dev-deps,
    /// never in runtime deps.
    #[cfg(any(test, feature = "test-utils"))]
    pub fn route_state(&self) -> &HashMap<String, PeerRouteState> {
        &self.route_state
    }
}
