"""Regression tests for the SLURM wrapper script generated by
:meth:`SlurmJobManager.generate_wrapper_script`.

These guard against two field-driven hardenings that were silently
dropped during a prior wrapper-template rewrite:

1. ``--pull=never`` on every ``podman run`` (commit 48288f7).
   Without it, an incomplete ``podman load`` falls through to
   ``docker.io/library/<image>``, hangs for minutes on access-denied,
   and bleeds the dispatcher's SecondaryWelcome timeout budget.

2. ``trap cleanup EXIT TERM HUP INT`` (commit 485629c). EXIT alone
   misses every SLURM-induced termination (sbatch time-limit →
   SIGTERM, ssh disconnect → SIGHUP, Ctrl+C → SIGINT) and leaks
   ``/tmp/asm-XXXX`` scratch dirs across the cluster.

The test asserts the rendered wrapper-string contains both, so the
next wrapper rewrite that drops either one fails CI loudly.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from dynamic_runner.deployment_spec import TaskDeploymentSpec
from dynamic_runner.packaging.job_manager import SlurmJobManager
from dynamic_runner.packaging.podman import PodmanImageMetadata, PodmanPackaging
from dynamic_runner.packaging.slurm_config import SlurmConfig


def _extract_podman_run_invocations(wrapper: str) -> list[str]:
    """Pull out each full ``podman ... run --rm ...`` invocation as one
    string with bash line continuations (``\\\n``) folded so we can
    check argument presence directly. Stops at the first non-continued
    newline (i.e. the actual end of the shell command)."""
    invocations: list[str] = []
    # Match the start of a podman-run line and greedily consume
    # continuation lines (lines ending in `\`) up to a real newline.
    pattern = re.compile(r"podman[^\n]*run --rm(?:[^\n]*\\\n)*[^\n]*", re.MULTILINE)
    for m in pattern.finditer(wrapper):
        # Fold continuations into a single logical line for the
        # presence check.
        invocations.append(m.group(0).replace("\\\n", " "))
    return invocations


_TEST_DEPLOYMENT = TaskDeploymentSpec(
    secondary_module="test_pkg",
    image_name="test-image",
)


class _StubGateway:
    """Minimal gateway stub. ``generate_wrapper_script`` only ever
    consults ``remote_home`` (via ``_expand_path``) and never calls
    ``execute_command`` / ``transfer_file`` itself, so a no-op is
    sufficient."""

    remote_home = "/home/test"
    host = "gateway.example"


@pytest.fixture
def manager(tmp_path: Path) -> SlurmJobManager:
    slurm_config = SlurmConfig(root_folder=str(tmp_path / "slurm-root"))
    packaging = PodmanPackaging(deployment=_TEST_DEPLOYMENT)
    return SlurmJobManager(
        gateway=_StubGateway(),
        slurm_config=slurm_config,
        packaging_method=packaging,
        deployment=_TEST_DEPLOYMENT,
    )


@pytest.fixture
def image_metadata(tmp_path: Path) -> PodmanImageMetadata:
    return PodmanImageMetadata(
        remote_path=tmp_path / "image.tar",
        image_hash="0" * 64,
        uploaded=False,
    )


@pytest.mark.parametrize("reverse_connection", [False, True])
def test_wrapper_has_pull_never_on_every_podman_run(
    manager: SlurmJobManager,
    image_metadata: PodmanImageMetadata,
    reverse_connection: bool,
) -> None:
    """Every ``podman run`` invocation in the rendered wrapper must
    include ``--pull=never``. Both connection modes render exactly
    one ``podman run`` line (reverse-mode and standard-mode are
    mutually exclusive branches). Checked at the *invocation* level
    (i.e. as an actual flag in the argument list) so a comment
    mentioning ``--pull=never`` doesn't satisfy the assertion."""
    wrapper = manager.generate_wrapper_script(
        image_metadata=image_metadata,
        secondary_id="secondary-0",
        gateway_host="gateway.example",
        gateway_port=12345,
        reverse_connection=reverse_connection,
    )

    invocations = _extract_podman_run_invocations(wrapper)
    assert invocations, "expected at least one `podman run --rm` invocation in wrapper"

    for i, inv in enumerate(invocations):
        assert "--pull=never" in inv, (
            f"`podman run` invocation #{i} is missing the `--pull=never` flag "
            "(see commit 48288f7 for rationale). Invocation:\n" + inv
        )


@pytest.mark.parametrize("reverse_connection", [False, True])
def test_wrapper_traps_termination_signals(
    manager: SlurmJobManager,
    image_metadata: PodmanImageMetadata,
    reverse_connection: bool,
) -> None:
    """The wrapper's cleanup trap must fire on SLURM-induced
    terminations (TERM/HUP/INT), not just graceful EXIT, otherwise
    /tmp/asm-XXXX scratch dirs accumulate on multi-day clusters
    (see commit 485629c)."""
    wrapper = manager.generate_wrapper_script(
        image_metadata=image_metadata,
        secondary_id="secondary-0",
        gateway_host="gateway.example",
        gateway_port=12345,
        reverse_connection=reverse_connection,
    )

    assert "trap cleanup EXIT TERM HUP INT" in wrapper, (
        "wrapper trap must include TERM/HUP/INT in addition to EXIT — "
        "EXIT alone misses every SLURM-induced termination "
        "(see commit 485629c for rationale)"
    )


def test_test_wrapper_traps_termination_signals(
    manager: SlurmJobManager,
    image_metadata: PodmanImageMetadata,
) -> None:
    """The image-validation test wrapper must also use the
    full-signal trap. It's used by ``slurm-validate-image`` from a
    sibling code path, and the same /tmp-leak class applies."""
    wrapper = manager.generate_test_wrapper_script(image_metadata=image_metadata)

    assert "trap cleanup EXIT TERM HUP INT" in wrapper, (
        "test wrapper trap must include TERM/HUP/INT in addition to EXIT"
    )
