"""Regression tests for the SLURM wrapper script generated by
:meth:`SlurmJobManager.generate_wrapper_script`.

These guard against three field-driven behaviours that the wrapper
template MUST keep stable:

1. ``--pull=never`` on every ``podman run`` (commit 48288f7).
   Without it, an incomplete ``podman load`` falls through to
   ``docker.io/library/<image>``, hangs for minutes on access-denied,
   and bleeds the dispatcher's SecondaryWelcome timeout budget.

2. ``trap cleanup EXIT TERM HUP INT`` (commit 485629c). EXIT alone
   misses every SLURM-induced termination (sbatch time-limit →
   SIGTERM, ssh disconnect → SIGHUP, Ctrl+C → SIGINT) and leaks
   ``/tmp/asm-XXXX`` scratch dirs across the cluster.

3. ``TaskDeploymentSpec.extra_run_args`` flows into the ``podman run``
   invocation BEFORE the ``{image_name}:{image_tag}`` argument and
   AFTER the framework's own flags. Default ``()`` produces no
   change to the rendered script; non-empty tuple appears verbatim
   (with bash-quoting via :func:`shlex.quote`) in BOTH
   ``reverse_connection`` branches.

The test asserts the rendered wrapper-string honours all three, so the
next wrapper rewrite that breaks any of them fails CI loudly.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from dynamic_runner.deployment_spec import TaskDeploymentSpec
from dynamic_runner.packaging.job_manager import SlurmJobManager
from dynamic_runner.packaging.podman import PodmanImageMetadata, PodmanPackaging
from dynamic_runner.packaging.slurm_config import SlurmConfig


def _extract_podman_run_invocations(wrapper: str) -> list[str]:
    """Pull out each full ``podman ... run --rm ...`` invocation as one
    string with bash line continuations (``\\\n``) folded so we can
    check argument presence directly. Stops at the first non-continued
    newline (i.e. the actual end of the shell command)."""
    invocations: list[str] = []
    # Match the start of a podman-run line and greedily consume
    # continuation lines (lines ending in `\`) up to a real newline.
    pattern = re.compile(r"podman[^\n]*run --rm(?:[^\n]*\\\n)*[^\n]*", re.MULTILINE)
    for m in pattern.finditer(wrapper):
        # Fold continuations into a single logical line for the
        # presence check.
        invocations.append(m.group(0).replace("\\\n", " "))
    return invocations


_TEST_DEPLOYMENT = TaskDeploymentSpec(
    secondary_module="test_pkg",
    image_name="test-image",
)


class _StubGateway:
    """Minimal gateway stub. ``generate_wrapper_script`` only ever
    consults ``remote_home`` (via ``_expand_path``) and never calls
    ``execute_command`` / ``transfer_file`` itself, so a no-op is
    sufficient."""

    remote_home = "/home/test"
    host = "gateway.example"


@pytest.fixture
def manager(tmp_path: Path) -> SlurmJobManager:
    slurm_config = SlurmConfig(root_folder=str(tmp_path / "slurm-root"))
    packaging = PodmanPackaging(deployment=_TEST_DEPLOYMENT)
    return SlurmJobManager(
        gateway=_StubGateway(),
        slurm_config=slurm_config,
        packaging_method=packaging,
        deployment=_TEST_DEPLOYMENT,
    )


@pytest.fixture
def image_metadata(tmp_path: Path) -> PodmanImageMetadata:
    return PodmanImageMetadata(
        remote_path=tmp_path / "image.tar",
        image_hash="0" * 64,
        uploaded=False,
    )


@pytest.mark.parametrize("reverse_connection", [False, True])
def test_wrapper_has_pull_never_on_every_podman_run(
    manager: SlurmJobManager,
    image_metadata: PodmanImageMetadata,
    reverse_connection: bool,
) -> None:
    """Every ``podman run`` invocation in the rendered wrapper must
    include ``--pull=never``. Both connection modes render exactly
    one ``podman run`` line (reverse-mode and standard-mode are
    mutually exclusive branches). Checked at the *invocation* level
    (i.e. as an actual flag in the argument list) so a comment
    mentioning ``--pull=never`` doesn't satisfy the assertion."""
    wrapper = manager.generate_wrapper_script(
        image_metadata=image_metadata,
        secondary_id="secondary-0",
        gateway_host="gateway.example",
        gateway_port=12345,
        reverse_connection=reverse_connection,
    )

    invocations = _extract_podman_run_invocations(wrapper)
    assert invocations, "expected at least one `podman run --rm` invocation in wrapper"

    for i, inv in enumerate(invocations):
        assert "--pull=never" in inv, (
            f"`podman run` invocation #{i} is missing the `--pull=never` flag "
            "(see commit 48288f7 for rationale). Invocation:\n" + inv
        )


@pytest.mark.parametrize("reverse_connection", [False, True])
def test_wrapper_traps_termination_signals(
    manager: SlurmJobManager,
    image_metadata: PodmanImageMetadata,
    reverse_connection: bool,
) -> None:
    """The wrapper's cleanup trap must fire on SLURM-induced
    terminations (TERM/HUP/INT), not just graceful EXIT, otherwise
    /tmp/asm-XXXX scratch dirs accumulate on multi-day clusters
    (see commit 485629c)."""
    wrapper = manager.generate_wrapper_script(
        image_metadata=image_metadata,
        secondary_id="secondary-0",
        gateway_host="gateway.example",
        gateway_port=12345,
        reverse_connection=reverse_connection,
    )

    assert "trap cleanup EXIT TERM HUP INT" in wrapper, (
        "wrapper trap must include TERM/HUP/INT in addition to EXIT — "
        "EXIT alone misses every SLURM-induced termination "
        "(see commit 485629c for rationale)"
    )


def test_test_wrapper_traps_termination_signals(
    manager: SlurmJobManager,
    image_metadata: PodmanImageMetadata,
) -> None:
    """The image-validation test wrapper must also use the
    full-signal trap. It's used by ``slurm-validate-image`` from a
    sibling code path, and the same /tmp-leak class applies."""
    wrapper = manager.generate_test_wrapper_script(image_metadata=image_metadata)

    assert "trap cleanup EXIT TERM HUP INT" in wrapper, (
        "test wrapper trap must include TERM/HUP/INT in addition to EXIT"
    )


def _build_manager(
    tmp_path: Path,
    extra_run_args: tuple[str, ...],
) -> SlurmJobManager:
    """Build a :class:`SlurmJobManager` whose deployment carries the
    requested ``extra_run_args``. Mirrors the ``manager`` fixture but
    parametrises the deployment field — kept separate so the existing
    fixture-based tests remain unchanged."""
    deployment = TaskDeploymentSpec(
        secondary_module="test_pkg",
        image_name="test-image",
        extra_run_args=extra_run_args,
    )
    slurm_config = SlurmConfig(root_folder=str(tmp_path / "slurm-root"))
    packaging = PodmanPackaging(deployment=deployment)
    return SlurmJobManager(
        gateway=_StubGateway(),
        slurm_config=slurm_config,
        packaging_method=packaging,
        deployment=deployment,
    )


@pytest.mark.parametrize("reverse_connection", [False, True])
def test_wrapper_omits_extra_run_args_when_default(
    tmp_path: Path,
    image_metadata: PodmanImageMetadata,
    reverse_connection: bool,
) -> None:
    """With the default ``extra_run_args=()`` the rendered wrapper
    must not gain any extra flags between the env/volume block and
    the image-tag argument. Exact-string check on a few flag tokens
    we know consumers use as the canonical examples; their absence
    proves the empty-tuple path is a true no-op."""
    manager = _build_manager(tmp_path, extra_run_args=())
    wrapper = manager.generate_wrapper_script(
        image_metadata=image_metadata,
        secondary_id="secondary-0",
        gateway_host="gateway.example",
        gateway_port=12345,
        reverse_connection=reverse_connection,
    )

    invocations = _extract_podman_run_invocations(wrapper)
    assert invocations, "expected at least one `podman run --rm` invocation in wrapper"
    for inv in invocations:
        assert "--pids-limit" not in inv, (
            "default `extra_run_args=()` must not inject any flags into the "
            "podman-run line; found `--pids-limit` in:\n" + inv
        )
        assert "--ulimit" not in inv, (
            "default `extra_run_args=()` must not inject any flags into the "
            "podman-run line; found `--ulimit` in:\n" + inv
        )


@pytest.mark.parametrize("reverse_connection", [False, True])
def test_wrapper_injects_extra_run_args_before_image_tag(
    tmp_path: Path,
    image_metadata: PodmanImageMetadata,
    reverse_connection: bool,
) -> None:
    """Each entry of ``TaskDeploymentSpec.extra_run_args`` must
    appear in the rendered ``podman run`` invocation BEFORE the
    ``{image_name}:{image_tag}`` argument and AFTER the framework's
    own flags. Both connection branches receive the same injection.

    The pids-limit case is the dataset peer's concrete trigger:
    Krater rootless podman defaults to 2048 PIDs, which a 64-way
    autotools fanout (nmap-style builds) blows through during
    parallel ``./configure`` + sub-``make`` spawn storms. The
    framework can't auto-derive this from system probe (it's a
    workload property, not a host property), so the consumer is
    the right party to supply it."""
    extra = ("--pids-limit=16384", "--ulimit=nofile=65536")
    manager = _build_manager(tmp_path, extra_run_args=extra)
    wrapper = manager.generate_wrapper_script(
        image_metadata=image_metadata,
        secondary_id="secondary-0",
        gateway_host="gateway.example",
        gateway_port=12345,
        reverse_connection=reverse_connection,
    )

    invocations = _extract_podman_run_invocations(wrapper)
    assert invocations, "expected at least one `podman run --rm` invocation in wrapper"

    image_ref = "test-image:latest"
    for i, inv in enumerate(invocations):
        for flag in extra:
            assert flag in inv, (
                f"`podman run` invocation #{i} is missing extra_run_args entry "
                f"{flag!r}. Invocation:\n" + inv
            )
            # Order check: each extra arg must precede the image
            # ref. podman parses args left-to-right and treats the
            # first non-flag token as the image, so anything after
            # the image ref would be interpreted as part of the
            # in-container command.
            assert inv.index(flag) < inv.index(image_ref), (
                f"`podman run` invocation #{i}: extra_run_args entry {flag!r} "
                f"appears AFTER the image ref {image_ref!r}; podman would "
                "treat it as part of the container command. Invocation:\n"
                + inv
            )
