"""Regression tests for the SLURM wrapper script generated by
:meth:`SlurmJobManager.generate_wrapper_script`.

These guard against three field-driven behaviours that the wrapper
template MUST keep stable:

1. ``--pull=never`` on every ``podman run`` (commit 48288f7).
   Without it, an incomplete ``podman load`` falls through to
   ``docker.io/library/<image>``, hangs for minutes on access-denied,
   and bleeds the dispatcher's SecondaryWelcome timeout budget.

2. ``trap cleanup EXIT TERM HUP INT`` (commit 485629c). EXIT alone
   misses every SLURM-induced termination (sbatch time-limit →
   SIGTERM, ssh disconnect → SIGHUP, Ctrl+C → SIGINT) and leaks
   ``/tmp/asm-XXXX`` scratch dirs across the cluster.

3. ``TaskDeploymentSpec.extra_run_args`` flows into the ``podman run``
   invocation BEFORE the ``{image_name}:{image_tag}`` argument and
   AFTER the framework's own flags. Default ``()`` produces no
   change to the rendered script; non-empty tuple appears verbatim
   (with bash-quoting via :func:`shlex.quote`) in BOTH
   ``reverse_connection`` branches.

The test asserts the rendered wrapper-string honours all three, so the
next wrapper rewrite that breaks any of them fails CI loudly.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from dynamic_runner.deployment_spec import TaskDeploymentSpec
from dynamic_runner.packaging.job_manager import SlurmJobManager
from dynamic_runner.packaging.podman import PodmanImageMetadata, PodmanPackaging
from dynamic_runner.packaging.slurm_config import SlurmConfig


def _extract_podman_run_invocations(wrapper: str) -> list[str]:
    """Pull out each full ``podman ... run --rm ...`` invocation as one
    string with bash line continuations (``\\\n``) folded so we can
    check argument presence directly. Stops at the first non-continued
    newline (i.e. the actual end of the shell command)."""
    invocations: list[str] = []
    # Match the start of a podman-run line and greedily consume
    # continuation lines (lines ending in `\`) up to a real newline.
    pattern = re.compile(r"podman[^\n]*run --rm(?:[^\n]*\\\n)*[^\n]*", re.MULTILINE)
    for m in pattern.finditer(wrapper):
        # Fold continuations into a single logical line for the
        # presence check.
        invocations.append(m.group(0).replace("\\\n", " "))
    return invocations


_TEST_DEPLOYMENT = TaskDeploymentSpec(
    secondary_module="test_pkg",
    image_name="test-image",
)


class _StubGateway:
    """Minimal gateway stub. ``generate_wrapper_script`` only ever
    consults ``remote_home`` (via ``_expand_path``) and never calls
    ``execute_command`` / ``transfer_file`` itself, so a no-op is
    sufficient."""

    remote_home = "/home/test"
    host = "gateway.example"


@pytest.fixture
def manager(tmp_path: Path) -> SlurmJobManager:
    slurm_config = SlurmConfig(root_folder=str(tmp_path / "slurm-root"))
    packaging = PodmanPackaging(deployment=_TEST_DEPLOYMENT)
    return SlurmJobManager(
        gateway=_StubGateway(),
        slurm_config=slurm_config,
        packaging_method=packaging,
        deployment=_TEST_DEPLOYMENT,
    )


@pytest.fixture
def image_metadata(tmp_path: Path) -> PodmanImageMetadata:
    return PodmanImageMetadata(
        remote_path=tmp_path / "image.tar",
        image_hash="0" * 64,
        uploaded=False,
    )


@pytest.mark.parametrize("reverse_connection", [False, True])
def test_wrapper_has_pull_never_on_every_podman_run(
    manager: SlurmJobManager,
    image_metadata: PodmanImageMetadata,
    reverse_connection: bool,
) -> None:
    """Every ``podman run`` invocation in the rendered wrapper must
    include ``--pull=never``. Both connection modes render exactly
    one ``podman run`` line (reverse-mode and standard-mode are
    mutually exclusive branches). Checked at the *invocation* level
    (i.e. as an actual flag in the argument list) so a comment
    mentioning ``--pull=never`` doesn't satisfy the assertion."""
    wrapper = manager.generate_wrapper_script(
        image_metadata=image_metadata,
        secondary_id="secondary-0",
        gateway_host="gateway.example",
        gateway_port=12345,
        reverse_connection=reverse_connection,
    )

    invocations = _extract_podman_run_invocations(wrapper)
    assert invocations, "expected at least one `podman run --rm` invocation in wrapper"

    for i, inv in enumerate(invocations):
        assert "--pull=never" in inv, (
            f"`podman run` invocation #{i} is missing the `--pull=never` flag "
            "(see commit 48288f7 for rationale). Invocation:\n" + inv
        )


@pytest.mark.parametrize("reverse_connection", [False, True])
def test_wrapper_traps_termination_signals(
    manager: SlurmJobManager,
    image_metadata: PodmanImageMetadata,
    reverse_connection: bool,
) -> None:
    """The wrapper's cleanup trap must fire on SLURM-induced
    terminations (TERM/HUP/INT), not just graceful EXIT, otherwise
    /tmp/asm-XXXX scratch dirs accumulate on multi-day clusters
    (see commit 485629c)."""
    wrapper = manager.generate_wrapper_script(
        image_metadata=image_metadata,
        secondary_id="secondary-0",
        gateway_host="gateway.example",
        gateway_port=12345,
        reverse_connection=reverse_connection,
    )

    assert "trap cleanup EXIT TERM HUP INT" in wrapper, (
        "wrapper trap must include TERM/HUP/INT in addition to EXIT — "
        "EXIT alone misses every SLURM-induced termination "
        "(see commit 485629c for rationale)"
    )


def test_test_wrapper_traps_termination_signals(
    manager: SlurmJobManager,
    image_metadata: PodmanImageMetadata,
) -> None:
    """The image-validation test wrapper must also use the
    full-signal trap. It's used by ``slurm-validate-image`` from a
    sibling code path, and the same /tmp-leak class applies."""
    wrapper = manager.generate_test_wrapper_script(image_metadata=image_metadata)

    assert "trap cleanup EXIT TERM HUP INT" in wrapper, (
        "test wrapper trap must include TERM/HUP/INT in addition to EXIT"
    )


def _build_manager(
    tmp_path: Path,
    extra_run_args: tuple[str, ...],
) -> SlurmJobManager:
    """Build a :class:`SlurmJobManager` whose deployment carries the
    requested ``extra_run_args``. Mirrors the ``manager`` fixture but
    parametrises the deployment field — kept separate so the existing
    fixture-based tests remain unchanged."""
    deployment = TaskDeploymentSpec(
        secondary_module="test_pkg",
        image_name="test-image",
        extra_run_args=extra_run_args,
    )
    slurm_config = SlurmConfig(root_folder=str(tmp_path / "slurm-root"))
    packaging = PodmanPackaging(deployment=deployment)
    return SlurmJobManager(
        gateway=_StubGateway(),
        slurm_config=slurm_config,
        packaging_method=packaging,
        deployment=deployment,
    )


@pytest.mark.parametrize("reverse_connection", [False, True])
def test_wrapper_omits_extra_run_args_when_default(
    tmp_path: Path,
    image_metadata: PodmanImageMetadata,
    reverse_connection: bool,
) -> None:
    """With the default ``extra_run_args=()`` the rendered wrapper
    must not inject any *consumer*-supplied flags between the
    env/volume block and the image-tag argument. ``--pids-limit`` is
    NOT probed here — it became a framework default (see
    :func:`test_wrapper_emits_default_pids_limit`); ``--ulimit``,
    ``--cap-add``, and ``--shm-size`` remain pure consumer-side and
    must be absent on the empty-tuple path."""
    manager = _build_manager(tmp_path, extra_run_args=())
    wrapper = manager.generate_wrapper_script(
        image_metadata=image_metadata,
        secondary_id="secondary-0",
        gateway_host="gateway.example",
        gateway_port=12345,
        reverse_connection=reverse_connection,
    )

    invocations = _extract_podman_run_invocations(wrapper)
    assert invocations, "expected at least one `podman run --rm` invocation in wrapper"
    for inv in invocations:
        for consumer_only_flag in ("--ulimit", "--cap-add", "--shm-size"):
            assert consumer_only_flag not in inv, (
                f"default `extra_run_args=()` must not inject {consumer_only_flag!r} "
                f"into the podman-run line; found in:\n" + inv
            )


@pytest.mark.parametrize("reverse_connection", [False, True])
def test_wrapper_emits_default_pids_limit(
    tmp_path: Path,
    image_metadata: PodmanImageMetadata,
    reverse_connection: bool,
) -> None:
    """Every rendered ``podman run`` invocation must carry the
    framework default ``--pids-limit=16384``, with or without
    consumer-supplied ``extra_run_args``. Rationale: podman rootless
    defaults to 2048 PIDs, which is too tight for both compile-heavy
    fanout (autotools + parallel gcc/clang) and JVM-heavy workloads
    (Ghidra spawns native threads counted against ``pids.max``). Both
    consumer teams hit this; making it the framework default saves
    every consumer from rediscovering it. Override path is documented
    on ``TaskDeploymentSpec.extra_run_args``."""
    manager = _build_manager(tmp_path, extra_run_args=())
    wrapper = manager.generate_wrapper_script(
        image_metadata=image_metadata,
        secondary_id="secondary-0",
        gateway_host="gateway.example",
        gateway_port=12345,
        reverse_connection=reverse_connection,
    )

    invocations = _extract_podman_run_invocations(wrapper)
    assert invocations, "expected at least one `podman run --rm` invocation in wrapper"
    for i, inv in enumerate(invocations):
        assert "--pids-limit=16384" in inv, (
            f"`podman run` invocation #{i} is missing the framework default "
            "`--pids-limit=16384` flag. Invocation:\n" + inv
        )


@pytest.mark.parametrize("reverse_connection", [False, True])
def test_wrapper_consumer_pids_limit_overrides_default(
    tmp_path: Path,
    image_metadata: PodmanImageMetadata,
    reverse_connection: bool,
) -> None:
    """A consumer that supplies ``--pids-limit=N`` via
    ``extra_run_args`` gets BOTH the framework default
    ``--pids-limit=16384`` AND their own value rendered into the
    invocation. podman applies the LAST occurrence of a flag, so the
    consumer's entry wins. The test asserts both appear and the
    consumer's value lands AFTER the default — the order podman uses
    to pick the effective value."""
    consumer_value = "--pids-limit=65536"
    manager = _build_manager(tmp_path, extra_run_args=(consumer_value,))
    wrapper = manager.generate_wrapper_script(
        image_metadata=image_metadata,
        secondary_id="secondary-0",
        gateway_host="gateway.example",
        gateway_port=12345,
        reverse_connection=reverse_connection,
    )

    invocations = _extract_podman_run_invocations(wrapper)
    assert invocations, "expected at least one `podman run --rm` invocation in wrapper"
    for i, inv in enumerate(invocations):
        default_idx = inv.index("--pids-limit=16384")
        consumer_idx = inv.index(consumer_value)
        assert default_idx < consumer_idx, (
            f"`podman run` invocation #{i}: consumer-supplied {consumer_value!r} "
            "must appear AFTER the framework default `--pids-limit=16384` so "
            "podman's last-wins parsing applies the consumer's value. "
            "Invocation:\n" + inv
        )


@pytest.mark.parametrize("reverse_connection", [False, True])
def test_wrapper_injects_extra_run_args_before_image_tag(
    tmp_path: Path,
    image_metadata: PodmanImageMetadata,
    reverse_connection: bool,
) -> None:
    """Each entry of ``TaskDeploymentSpec.extra_run_args`` must
    appear in the rendered ``podman run`` invocation BEFORE the
    ``{image_name}:{image_tag}`` argument and AFTER the framework's
    own flags. Both connection branches receive the same injection.

    Uses ``--ulimit`` and ``--shm-size`` as the canonical
    consumer-only flags (``--pids-limit`` is now a framework default;
    its override-and-last-wins behaviour is exercised by
    :func:`test_wrapper_consumer_pids_limit_overrides_default`)."""
    extra = ("--ulimit=nofile=65536", "--shm-size=2g")
    manager = _build_manager(tmp_path, extra_run_args=extra)
    wrapper = manager.generate_wrapper_script(
        image_metadata=image_metadata,
        secondary_id="secondary-0",
        gateway_host="gateway.example",
        gateway_port=12345,
        reverse_connection=reverse_connection,
    )

    invocations = _extract_podman_run_invocations(wrapper)
    assert invocations, "expected at least one `podman run --rm` invocation in wrapper"

    image_ref = "test-image:latest"
    for i, inv in enumerate(invocations):
        for flag in extra:
            assert flag in inv, (
                f"`podman run` invocation #{i} is missing extra_run_args entry "
                f"{flag!r}. Invocation:\n" + inv
            )
            # Order check: each extra arg must precede the image
            # ref. podman parses args left-to-right and treats the
            # first non-flag token as the image, so anything after
            # the image ref would be interpreted as part of the
            # in-container command.
            assert inv.index(flag) < inv.index(image_ref), (
                f"`podman run` invocation #{i}: extra_run_args entry {flag!r} "
                f"appears AFTER the image ref {image_ref!r}; podman would "
                "treat it as part of the container command. Invocation:\n"
                + inv
            )


@pytest.mark.parametrize("reverse_connection", [False, True])
def test_wrapper_names_container_for_teardown_addressability(
    manager: SlurmJobManager,
    image_metadata: PodmanImageMetadata,
    reverse_connection: bool,
) -> None:
    """The wrapper must define ``CONTAINER_NAME`` and pass it to
    ``podman run`` via ``--name "$CONTAINER_NAME"``. Without a stable
    name the fallback teardown watchdog has no handle to issue
    ``podman kill``/``podman rm`` against — podman would assign an
    auto-generated name (e.g. ``eloquent_solomon``) that the watchdog
    doesn't know in advance.

    The accompanying test
    :func:`test_wrapper_spawns_podman_teardown_watchdog` covers the
    watchdog itself; this one guards the addressability precondition."""
    wrapper = manager.generate_wrapper_script(
        image_metadata=image_metadata,
        secondary_id="secondary-0",
        gateway_host="gateway.example",
        gateway_port=12345,
        reverse_connection=reverse_connection,
    )

    assert re.search(r'^CONTAINER_NAME="[^"]+"\s*$', wrapper, re.MULTILINE), (
        "wrapper must assign CONTAINER_NAME to a non-empty literal so the "
        "fallback teardown watchdog can address the container by name"
    )

    invocations = _extract_podman_run_invocations(wrapper)
    assert invocations, "expected at least one `podman run --rm` invocation in wrapper"
    for i, inv in enumerate(invocations):
        assert '--name "$CONTAINER_NAME"' in inv, (
            f"`podman run` invocation #{i} is missing `--name \"$CONTAINER_NAME\"`; "
            "without it the container has only an auto-generated name and the "
            "fallback teardown watchdog can't kill it.\nInvocation:\n" + inv
        )


@pytest.mark.parametrize("reverse_connection", [False, True])
def test_wrapper_spawns_podman_teardown_watchdog(
    manager: SlurmJobManager,
    image_metadata: PodmanImageMetadata,
    reverse_connection: bool,
) -> None:
    """Field observation: when scancel hits a job whose secondary
    runs a podman container, conmon's double-fork detaches the
    container monitor from the slurmstepd pidtree. If proctrack/cgroup
    isn't tracking conmon's detached pid, neither scancel nor wrapper
    exit propagate into the container and it survives both the
    wrapper and the SLURM job, leaking storage and worker pids on
    the compute node.

    The wrapper installs a fallback teardown watchdog: a ``setsid -f``
    detached process that polls ``squeue -j $SLURM_JOB_ID`` and runs
    ``podman kill`` + ``podman rm -f`` on this container by name when
    the job is gone. This test guards each ingredient of that
    mechanism so a future refactor can't silently drop one of them
    and reintroduce the leak."""
    wrapper = manager.generate_wrapper_script(
        image_metadata=image_metadata,
        secondary_id="secondary-0",
        gateway_host="gateway.example",
        gateway_port=12345,
        reverse_connection=reverse_connection,
    )

    # Detached spawn: setsid -f puts the watchdog in its own session
    # with init as parent so it survives wrapper exit (and, where
    # cgroup proctrack permits, SLURM job termination).
    assert "setsid -f bash -c" in wrapper, (
        "watchdog must be spawned via `setsid -f bash -c '…'` so it survives "
        "the wrapper's exit and runs detached as the conmon-evades-cgroup "
        "fallback teardown"
    )

    # Job-state polling: squeue is the source of truth for whether
    # the SLURM job is still alive. The watchdog must distinguish
    # `exit 0 + empty stdout` (job genuinely gone) from `exit nonzero`
    # (transient query failure → keep polling).
    assert "squeue -j" in wrapper, (
        "watchdog must poll `squeue -j $SLURM_JOB_ID` to observe job state"
    )

    # Teardown sequence: TERM first to give the container a chance to
    # shut down cleanly, then `rm -f` as belt-and-suspenders if --rm
    # didn't fire (e.g. conmon was in a bad state).
    assert "podman" in wrapper and "kill --signal TERM" in wrapper, (
        "watchdog must issue `podman kill --signal TERM <name>` on detected "
        "job-gone state"
    )
    assert "rm -f" in wrapper, (
        "watchdog must follow the kill with `podman rm -f <name>` to clean up "
        "container storage if --rm didn't auto-remove"
    )

    # Skip-when-not-in-SLURM guard: running the wrapper outside SLURM
    # (e.g. for local debugging) leaves SLURM_JOB_ID unset; without
    # the guard the watchdog would call `squeue -j ""` forever and
    # never trigger the cleanup branch.
    assert 'if [ -n "${SLURM_JOB_ID:-}" ]' in wrapper, (
        "watchdog must be guarded by `[ -n \"${SLURM_JOB_ID:-}\" ]` so it's "
        "skipped when running outside SLURM (where squeue would never find "
        "a matching job and the watchdog would poll indefinitely)"
    )


@pytest.mark.parametrize("reverse_connection", [False, True])
def test_wrapper_cleanup_kills_relay_subshell(
    manager: SlurmJobManager,
    image_metadata: PodmanImageMetadata,
    reverse_connection: bool,
) -> None:
    """The cleanup trap must terminate ``$CMD_RELAY_PID`` BEFORE the
    rm-rf, otherwise the relay subshell's ``read -r CMD < <fifo>``
    busy-spins on a deleted FIFO at ~50K iter/sec until something
    external kills it (run-8 reproduced this as a 110-minute spin
    producing 13 GB of stderr).

    Two-layer guard:
      1. cleanup() kills CMD_RELAY_PID (with ${...:-} for the
         early-failure path where the relay was never started),
      2. the relay loop's `while [ -p <fifo> ]` self-terminates
         if the FIFO disappears for any reason.

    Either layer alone closes the leak; both together cover signal
    races, external rms, and missed kills."""
    wrapper = manager.generate_wrapper_script(
        image_metadata=image_metadata,
        secondary_id="secondary-0",
        gateway_host="gateway.example",
        gateway_port=12345,
        reverse_connection=reverse_connection,
    )

    # Layer 1: cleanup trap kills the relay subshell.
    assert 'kill -TERM "$CMD_RELAY_PID"' in wrapper, (
        "cleanup() must kill CMD_RELAY_PID — without it the relay "
        "subshell busy-spins on the deleted FIFO after the trap fires"
    )
    assert '${CMD_RELAY_PID:-}' in wrapper, (
        "the kill must be guarded by `${CMD_RELAY_PID:-}` for the "
        "early-failure path where the relay was never started"
    )

    # Ordering: kill must precede the rm-rf so the FIFO is removed
    # only after the loop has stopped reading from it.
    kill_idx = wrapper.index('kill -TERM "$CMD_RELAY_PID"')
    rm_idx = wrapper.index('rm -rf "$RNDTMP"')
    assert kill_idx < rm_idx, (
        "cleanup() must kill the relay subshell BEFORE removing $RNDTMP "
        "so the rm doesn't race a still-spinning loop"
    )

    # Layer 2: the relay loop self-terminates if the FIFO disappears.
    # Positive check only — `while true` survives elsewhere in the
    # wrapper (e.g. the watchdog's squeue-poll loop, which has an
    # internal `break`); we just need the relay loop specifically to
    # be the `while [ -p <fifo> ]` shape.
    assert re.search(r'while \[ -p "[^"]+" \]; do\s+if read -r CMD', wrapper), (
        "relay loop must guard each iteration with `[ -p <fifo> ]` so it "
        "self-exits when the FIFO is gone"
    )


@pytest.mark.parametrize("reverse_connection", [False, True])
def test_wrapper_image_load_failure_is_visible(
    manager: SlurmJobManager,
    image_metadata: PodmanImageMetadata,
    reverse_connection: bool,
) -> None:
    """Image load is the wrapper's longest-running pre-container step
    and historically the most common point of opaque failure (large
    tarball, podman storage exhaustion, layer corruption). When it
    fails, the wrapper must surface a clear marker on STDOUT (not
    just rely on `set -e` aborting silently between echos), so an
    operator reading the .out file sees the failure rather than a
    "Loading…" line followed by a cleanup trap with no diagnostic."""
    wrapper = manager.generate_wrapper_script(
        image_metadata=image_metadata,
        secondary_id="secondary-0",
        gateway_host="gateway.example",
        gateway_port=12345,
        reverse_connection=reverse_connection,
    )

    # Failure check must be in place — `if ! <load_command>` is the
    # canonical shape that captures the exit code without tripping
    # set -e.
    assert "if ! podman" in wrapper and "load <" in wrapper, (
        "image load must be wrapped in `if ! <load_command>; then ... fi` "
        "so the wrapper can emit a visible failure marker before exiting; "
        "bare command + set -e gives no diagnostic on the .out file"
    )

    # Marker must reach stdout (the .out file consumers check first).
    assert re.search(r'echo\s+"ERROR: image load failed', wrapper), (
        "image-load failure must print a clear ERROR marker to stdout"
    )

    # Marker must also reach stderr (>&2) for log-aggregation tools
    # that watch stderr severity.
    assert ">&2" in wrapper and re.search(
        r'echo\s+"ERROR: image load failed[^"]*"\s*>&2', wrapper
    ), (
        "image-load failure must mirror the ERROR marker to stderr"
    )
